### ISSUE TITLE
Enter JS 2018

### ISSUE THREAD

**Issue by jblankenhorn** [w11k/ng-dropping-stones#13]
- Countdown 5 Sekunden bevor Spiel beginnt
- Game Over Screen
- Admin -> Gewinner anzeigen -> Feld größer machen

Namensformular
- Eingabefelder strg-a zeigt nicht die selektion an
- Enter soll ins nächste feld springen
- Invalide Email -> Start Knopf -> Zurücksprung in Email hat dort automatisch alles selektiert....

**Comment by ninaschulz** [comment]
![image](https://user-images.githubusercontent.com/48353891/54123195-5bf4c480-43ff-11e9-8d20-b87ed8da2224.png)
Blocks in der Vorschau haben eine Lücke

**Comment by fvonberg** [comment]
Done
